# SSB content domain configuration
from __future__ import annotations
from app.core.domain import ContentDomain, PlatformBranchConfig, TestDraftBranchConfig, TopicIntentRule

SSB_CONTENT_DOMAIN = ContentDomain(
    key="ssb",
    label="硕升博",
    topic_intent_rules=(
        TopicIntentRule(
            key="source_check",
            topic_terms=("来源", "核验", "认证", "官方", "核实", "信息源"),
            draft_terms=("核验", "来源", "官方", "待复核"),
            label="来源核验帖",
            guidance="强调信息来源的可信度和核验步骤，不做无来源的事实断言。",
        ),
        TopicIntentRule(
            key="list_filter",
            topic_terms=("排名", "榜单", "排行", "对比", "清单", "筛选"),
            draft_terms=("排名", "榜单", "对比", "维度", "筛选"),
            label="榜单筛选帖",
            guidance="提供多维度的筛选框架，不假装有内部排名。",
        ),
        TopicIntentRule(
            key="route",
            topic_terms=("路线", "在职", "海外", "水博", "申请路径", "出国"),
            draft_terms=("路线", "在职", "海外", "认证", "预算"),
            label="路线选择帖",
            guidance="拆解认证、预算、毕业难度、适配人群等维度。",
        ),
        TopicIntentRule(
            key="mentor",
            topic_terms=("导师", "导师匹配", "选导", "导师方向"),
            draft_terms=("导师", "方向", "匹配", "研究"),
            label="导师匹配帖",
            guidance="帮用户理清导师选择的关键维度。",
        ),
        TopicIntentRule(
            key="timeline",
            topic_terms=("时间线", "时间规划", "申请时间", "进度", "节点"),
            draft_terms=("时间", "节点", "规划", "截止"),
            label="时间线帖",
            guidance="按申请节点拆解时间线。",
        ),
        TopicIntentRule(
            key="sales",
            topic_terms=("含金量", "价值", "值得吗", "有必要", "意义"),
            draft_terms=("含金量", "价值", "投入", "回报"),
            label="价值评估帖",
            guidance="从投入产出比角度分析读博价值。",
        ),
        TopicIntentRule(
            key="pitfall",
            topic_terms=("避坑", "踩坑", "陷阱", "误区", "坑", "教训"),
            draft_terms=("坑", "避", "误区", "教训"),
            label="避坑提醒帖",
            guidance="提醒用户常见误区和陷阱，用真实案例说明。",
        ),
        TopicIntentRule(
            key="tutorial",
            topic_terms=("教程", "步骤", "怎么做", "操作", "流程", "指南"),
            draft_terms=("Step", "步骤", "流程", "操作"),
            label="操作教程帖",
            guidance="按步骤拆解操作流程，每步有明确产出。",
        ),
        TopicIntentRule(
            key="qa",
            topic_terms=("问答", "FAQ", "常见问题", "解答"),
            draft_terms=("Q", "问", "答"),
            label="高频问答帖",
            guidance="收集高频问题，每个问题给简洁回答。",
        ),
        TopicIntentRule(
            key="comparison",
            topic_terms=("对比", "比较", "vs", "VS", "差异", "区别", "哪个好"),
            draft_terms=("对比", "比较", "选项", "差异"),
            label="对比分析帖",
            guidance="多维度对比选项，给出适合人群建议。",
        ),
        TopicIntentRule(
            key="checklist",
            topic_terms=("清单", "checklist", "列表", "必备", "准备清单"),
            draft_terms=("清单", "列表", "准备"),
            label="清单帖",
            guidance="用清单形式整理必备事项，每项可执行。",
        ),
        TopicIntentRule(
            key="info_post",
            topic_terms=("通告", "通知", "招生", "简章", "名额", "招生简章", "招生通告", "博士招生"),
            draft_terms=("通告", "招生", "学校", "名额", "截止"),
            label="信息帖",
            guidance="基于高校招生通告发布信息帖，提供有价值的招生信息，建立专业形象，间接引流。",
        ),
    ),
    strong_topic_terms_by_rule={
        "source_check": ("官方", "认证", "核实"),
        "list_filter": ("排名", "榜单"),
        "route": ("水博", "在职博士", "海外博士"),
        "mentor": ("导师", "选导"),
        "timeline": ("时间线", "截止"),
        "sales": ("含金量", "值得吗"),
        "pitfall": ("避坑", "踩坑", "陷阱"),
        "tutorial": ("教程", "步骤", "指南"),
        "qa": ("问答", "FAQ"),
        "comparison": ("对比", "比较", "vs"),
        "checklist": ("清单", "checklist"),
        "info_post": ("招生", "通告", "简章"),
    },
    water_route_topic_terms=(
        "水博", "海外博士", "在职博士", "出国读博", "留学博士",
        "免联考博士", "国际博士", "DBA",
    ),
    ranking_topic_terms=(
        "排名", "榜单", "排行", "排行榜", "TOP", "top",
    ),
    ranking_draft_terms=(
        "认证", "预算", "毕业难度", "在职", "出勤",
        "论文", "答辩", "留服", "学费",
    ),
    forbidden_promotion_claims=[
        "guaranteed admission", "100%录取", "保录", "包过",
        "保证录取", "稳上", "内部名额",
    ],
    quality_checks=[
        "verification framework only",
        "no unsupported current-fact claims",
        "manual review required before publishing",
    ],
    brief_by_intent={
        "source_check": {
            "source_requirements": ["学校官网", "项目页面", "认证说明", "公开费用页"],
            "target_persona": "正在搜集博士申请信息的在职人群",
            "pain_point": "网上信息真假难辨，搬运帖太多",
            "trust_proof": "提供可核验的来源清单和核验步骤",
            "offer_angle": "来源核验框架，帮用户自己核实",
            "cta": "先收藏这份核验清单，再去查学校官网",
            "cover_angle": "清单式封面，突出核验维度",
            "success_metric": "用户能独立完成信息核验",
        },
        "list_filter": {
            "source_requirements": ["知识库条目", "Tavily 联网来源"],
            "target_persona": "在多个博士项目之间纠结的在职人群",
            "pain_point": "项目太多不知道怎么对比",
            "trust_proof": "提供多维度的筛选框架而非简单排名",
            "offer_angle": "按认证、预算、毕业难度、适配人群拆解",
            "cta": "先明确你的核心需求，再用这个框架筛选",
            "cover_angle": "对比表格封面",
            "success_metric": "用户能缩小候选范围",
        },
        "route": {
            "source_requirements": ["认证政策", "项目类型说明"],
            "target_persona": "考虑在职/海外读博的人群",
            "pain_point": "路线太多，不知道哪条适合自己",
            "trust_proof": "按认证、预算、毕业难度、适配人群四维拆解",
            "offer_angle": "路线对比框架，不替用户做决定",
            "cta": "先看认证和预算两个硬约束，再筛选",
            "cover_angle": "路线分叉图封面",
            "success_metric": "用户能初步锁定1-2条路线",
        },
        "mentor": {
            "source_requirements": ["导师研究方向", "院系页面"],
            "target_persona": "即将选导师的准博士生",
            "pain_point": "导师方向太散，不知道怎么匹配",
            "trust_proof": "提供导师匹配的关键维度清单",
            "offer_angle": "帮用户理清自己的研究兴趣和导师方向",
            "cta": "先列出你的研究关键词，再对照导师页面",
            "cover_angle": "匹配维度清单封面",
            "success_metric": "用户能列出3-5个候选导师",
        },
        "timeline": {
            "source_requirements": ["官方申请截止日期", "入学要求"],
            "target_persona": "准备启动申请的在职人群",
            "pain_point": "不知道什么时候该准备什么",
            "trust_proof": "按官方截止日期倒推时间线",
            "offer_angle": "申请时间线框架，标注关键节点",
            "cta": "先确认你的目标入学时间，再倒推",
            "cover_angle": "时间轴封面",
            "success_metric": "用户能制定初步申请计划",
        },
        "sales": {
            "source_requirements": ["投入产出数据", "真实案例"],
            "target_persona": "犹豫是否值得读博的在职人群",
            "pain_point": "投入大，不确定值不值",
            "trust_proof": "从含金量、投入、回报多维度分析",
            "offer_angle": "价值评估框架，不替用户下结论",
            "cta": "先算你的投入（时间+金钱+机会成本），再看回报",
            "cover_angle": "天平/投入产出比封面",
            "success_metric": "用户能做出理性判断",
        },
        "pitfall": {
            "source_requirements": ["真实案例", "用户反馈"],
            "target_persona": "正在准备博士申请的在职人群",
            "pain_point": "容易踩坑但不知道坑在哪",
            "trust_proof": "用真实案例说明常见误区",
            "offer_angle": "避坑清单，帮用户提前规避风险",
            "cta": "先收藏这份避坑清单，别犯同样的错",
            "cover_angle": "警告/避坑风格封面",
            "success_metric": "用户能识别并规避常见陷阱",
        },
        "tutorial": {
            "source_requirements": ["官方流程说明", "实操经验"],
            "target_persona": "需要操作指导的在职人群",
            "pain_point": "知道要做什么但不知道怎么做",
            "trust_proof": "按步骤拆解，每步有明确产出",
            "offer_angle": "操作教程，帮用户一步步完成",
            "cta": "跟着步骤来，每步给自己设deadline",
            "cover_angle": "步骤图/流程图封面",
            "success_metric": "用户能独立完成操作流程",
        },
        "qa": {
            "source_requirements": ["高频问题收集", "官方解答"],
            "target_persona": "有具体疑问的在职人群",
            "pain_point": "问题太多找不到答案",
            "trust_proof": "收集真实高频问题给简洁回答",
            "offer_angle": "问答合集，快速解决常见疑惑",
            "cta": "还有问题评论区见",
            "cover_angle": "问答风格封面",
            "success_metric": "用户能快速找到自己问题的答案",
        },
        "comparison": {
            "source_requirements": ["多维度数据", "真实案例"],
            "target_persona": "在多个选项间纠结的在职人群",
            "pain_point": "选项太多不知道怎么选",
            "trust_proof": "多维度对比，不替用户做决定",
            "offer_angle": "对比分析框架，帮用户看清差异",
            "cta": "先明确你的核心需求，再对照对比表",
            "cover_angle": "对比表格封面",
            "success_metric": "用户能缩小选择范围",
        },
        "checklist": {
            "source_requirements": ["官方要求", "经验总结"],
            "target_persona": "需要准备清单的在职人群",
            "pain_point": "不知道要准备什么",
            "trust_proof": "用清单形式整理必备事项",
            "offer_angle": "可执行清单，帮用户逐一准备",
            "cta": "先收藏这份清单，逐项准备",
            "cover_angle": "清单风格封面",
            "success_metric": "用户能按清单完成准备",
        },
        "info_post": {
            "source_requirements": ["高校招生通告", "官方网站"],
            "target_persona": "关注博士招生信息的在职人群",
            "pain_point": "招生信息分散，难以追踪截止日期和要求",
            "trust_proof": "引用官方招生通告，提供可核实的信息",
            "offer_angle": "整理招生信息，帮用户快速了解关键节点",
            "cta": "收藏这篇信息，点击链接查看原文",
            "cover_angle": "信息公告风格封面",
            "success_metric": "用户获得有价值的招生信息，建立信任",
        },
    },
    default_brief={
        "source_requirements": ["知识库条目", "Tavily 联网来源"],
        "target_persona": "在职考研/考博人群",
        "pain_point": "信息分散，缺乏系统梳理",
        "trust_proof": "基于知识库和联网来源提供结构化分析",
        "offer_angle": "提供框架和维度，帮用户自己判断",
        "cta": "先收藏这篇框架，后续持续补充",
        "cover_angle": "知识结构图封面",
        "success_metric": "用户获得清晰的决策框架",
    },
    missing_web_framework_terms=(
        "核验", "待复核", "官方来源", "来源缺失",
        "尚未确认", "信息待补", "人工核实",
    ),
    missing_web_fact_terms=(
        "学校名", "价格", "排名", "logo", "校徽",
        "学费", "具体金额", "录取率",
    ),
    draft_prompt_name="draft_generation",
    rewrite_prompt_name="humanization",
    test_draft_branches=TestDraftBranchConfig(
        xhs_water_ranking="xhs_water_ranking",
        xhs_missing_web_sources="xhs_missing_web_sources",
        xhs_default="xhs_default",
        water_ranking="water_ranking",
        default="default",
        intent_branch_map={
            "source_check": "xhs_source_check",
            "list_filter": "xhs_list_filter",
            "route": "xhs_route",
            "mentor": "xhs_mentor",
            "timeline": "xhs_timeline",
            "sales": "xhs_sales",
            "pitfall": "xhs_pitfall",
            "tutorial": "xhs_tutorial",
            "qa": "xhs_qa",
            "comparison": "xhs_comparison",
            "checklist": "xhs_checklist",
            "info_post": "xhs_info_post",
        },
        intent_subbranch_rules={
            "mentor": ((("散", "scattered", "太散"), "xhs_mentor_scattered"),),
            "sales": ((("含金量", "价值"), "xhs_sales_value"),),
        },
        non_xhs_intent_branch_map={
            "source_check": "source_check",
            "list_filter": "list_filter",
            "route": "route",
            "mentor": "mentor",
            "timeline": "timeline",
            "sales": "sales",
            "pitfall": "pitfall",
            "tutorial": "tutorial",
            "qa": "qa",
            "comparison": "comparison",
            "checklist": "checklist",
            "info_post": "info_post",
        },
        platform_configs={
            "xiaohongshu": PlatformBranchConfig(
                default="xhs_default",
                water_ranking="xhs_water_ranking",
                missing_web_sources="xhs_missing_web_sources",
                intent_map={
                    "source_check": "xhs_source_check",
                    "list_filter": "xhs_list_filter",
                    "route": "xhs_route",
                    "mentor": "xhs_mentor",
                    "timeline": "xhs_timeline",
                    "sales": "xhs_sales",
                    "pitfall": "xhs_pitfall",
                    "tutorial": "xhs_tutorial",
                    "qa": "xhs_qa",
                    "comparison": "xhs_comparison",
                    "checklist": "xhs_checklist",
                    "info_post": "xhs_info_post",
                },
                intent_subbranch_rules={
                    "mentor": ((("散", "scattered", "太散"), "xhs_mentor_scattered"),),
                    "sales": ((("含金量", "价值"), "xhs_sales_value"),),
                },
            ),
            "douyin": PlatformBranchConfig(
                default="dy_default",
                water_ranking="dy_water_ranking",
                missing_web_sources="dy_missing_web_sources",
                intent_map={
                    "source_check": "dy_source_check",
                    "list_filter": "dy_list_filter",
                    "route": "dy_route",
                    "mentor": "dy_mentor",
                    "timeline": "dy_timeline",
                    "sales": "dy_sales",
                    "pitfall": "dy_pitfall",
                    "tutorial": "dy_tutorial",
                    "qa": "dy_qa",
                    "comparison": "dy_comparison",
                    "checklist": "dy_checklist",
                    "info_post": "dy_info_post",
                },
                intent_subbranch_rules={
                    "mentor": ((("散", "scattered", "太散"), "dy_mentor_scattered"),),
                    "sales": ((("含金量", "价值"), "dy_sales_value"),),
                },
            ),
            "shipinhao": PlatformBranchConfig(
                default="sph_default",
                water_ranking="sph_water_ranking",
                missing_web_sources="sph_missing_web_sources",
                intent_map={
                    "source_check": "sph_source_check",
                    "list_filter": "sph_list_filter",
                    "route": "sph_route",
                    "mentor": "sph_mentor",
                    "timeline": "sph_timeline",
                    "sales": "sph_sales",
                    "pitfall": "sph_pitfall",
                    "tutorial": "sph_tutorial",
                    "qa": "sph_qa",
                    "comparison": "sph_comparison",
                    "checklist": "sph_checklist",
                    "info_post": "sph_info_post",
                },
                intent_subbranch_rules={
                    "mentor": ((("散", "scattered", "太散"), "sph_mentor_scattered"),),
                    "sales": ((("含金量", "价值"), "sph_sales_value"),),
                },
            ),
        },
    ),
    default_audience="在职考研/考博人群",
    default_tag_line="#硕升博 #在职博士 #水博",
)
